import 'dart:async';
import 'dart:io' show SecurityContext, X509Certificate;

import 'package:crypto/crypto.dart' show sha256;
import 'package:fixnum/fixnum.dart';
import 'package:grpc/grpc.dart';

import '../models/models.dart';
import '../state/device_list_model.dart' show DeviceListModel;
import 'connectible_exception.dart';
import 'server_identity.dart';
// Generated by tool/gen_proto.sh from ../proto/connectible.proto.
import '../generated/connectible.pbgrpc.dart' as pb;

/// [ChannelCredentials] that also presents this device's own identity
/// as the outbound TLS *client* certificate (Phase G, T-G6), alongside
/// the existing TOFU `onBadCertificate` handling for the *server*'s
/// cert. There is one identity per device (the same [ServerIdentity]
/// [ConnectibleServer] uses for its inbound role), presented in
/// whichever role this connection is playing.
class _MtlsChannelCredentials extends ChannelCredentials {
  _MtlsChannelCredentials({
    required this.identity,
    required super.onBadCertificate,
  }) : super.secure();

  final ServerIdentity identity;

  @override
  SecurityContext? get securityContext {
    final context = super.securityContext;
    if (context == null) return null;
    context.useCertificateChainBytes(identity.certBytes);
    context.usePrivateKeyBytes(identity.keyBytes);
    return context;
  }
}

class PairOutcome {
  const PairOutcome({required this.accepted, required this.pinExpiresAtMs});
  final bool accepted;
  final int pinExpiresAtMs;
}

/// gRPC client for talking to a remote Connectible daemon (T-044).
///
/// Trust model (MVP): the daemon presents a self-signed TLS 1.3
/// certificate, so the channel is created with an accept-any-cert
/// callback. This matches the documented MVP posture (PLAN.md
/// non-goals, RULES.md security checklist); certificate pinning
/// replaces it in v1.0. The handshake is still TLS 1.3 -- traffic is
/// encrypted, only chain identity is not verified.
class GrpcService {
  GrpcService._(this._channel, this._client, this._tofu);

  final ClientChannel _channel;
  final pb.ConnectibleClient _client;
  final _TofuState _tofu;

  /// Connects to a remote peer. TOFU (Phase C / T-C4): pass
  /// [pinnedFingerprint] (from the paired store) to require the peer to
  /// present that exact certificate -- a mismatch causes the TLS handshake
  /// (which happens lazily on the first RPC) to fail and sets
  /// [fingerprintMismatch]. Omit it for first contact / an unpinned device;
  /// the observed fingerprint is then captured in [observedFingerprint] so
  /// the caller can pin it (record-on-first-use).
  ///
  /// [identity] (Phase G, T-G6) is this device's own cert/key, presented
  /// as the outbound client certificate so the peer can pin *this*
  /// device's identity too, symmetrically -- the same identity
  /// [ConnectibleServer] uses for its inbound role.
  static Future<GrpcService> connect(
    String host,
    int port, {
    required ServerIdentity identity,
    String? pinnedFingerprint,
  }) async {
    final tofu = _TofuState(pinned: pinnedFingerprint);
    final channel = ClientChannel(
      host,
      port: port,
      options: ChannelOptions(
        credentials: _MtlsChannelCredentials(
          identity: identity,
          onBadCertificate: (cert, authority) => tofu.accept(cert),
        ),
        codecRegistry:
            CodecRegistry(codecs: const [GzipCodec(), IdentityCodec()]),
      ),
    );
    return GrpcService._(channel, pb.ConnectibleClient(channel), tofu);
  }

  /// The peer server cert fingerprint seen during the handshake (lowercase
  /// hex SHA-256 of the DER), or null if no handshake has happened yet.
  String? get observedFingerprint => _tofu.observed;

  /// True if the handshake was rejected because the presented cert did not
  /// match [pinnedFingerprint] (TOFU, T-C4). The caller maps this to a
  /// FINGERPRINT_CHANGED message rather than a generic connection failure.
  bool get fingerprintMismatch => _tofu.mismatch;

  pb.ConnectibleClient get raw => _client;

  int _nowMs() => DateTime.now().millisecondsSinceEpoch;

  Future<int> pingRttMs() async {
    final start = DateTime.now();
    await _client.ping(pb.PingRequest(sentAtMs: Int64(_nowMs())));
    return DateTime.now().difference(start).inMilliseconds;
  }

  Future<PairOutcome> pair(pb.Identity localIdentity) async {
    final resp = await _client.pair(pb.PairRequest(requester: localIdentity));
    if (resp.hasError()) {
      throw ConnectibleException.fromError(resp.error);
    }
    return PairOutcome(
      accepted: resp.accepted,
      pinExpiresAtMs: resp.pinExpiresAtMs.toInt(),
    );
  }

  /// Returns whether the PIN verified. On a rejection that carries a
  /// specific [pb.Error] (wrong PIN, expired window, ...) this throws the
  /// matching [ConnectibleException] subclass instead of just returning
  /// `false`, so callers that care can distinguish the reason; callers
  /// that only care about pass/fail can catch [ConnectibleException] and
  /// treat it as `false` (see `PairingModel.confirmPin`).
  Future<bool> confirmPin(String deviceId, String pinCode) async {
    final resp = await _client.confirmPin(
      pb.ConfirmPinRequest(deviceId: deviceId, pinCode: pinCode),
    );
    if (!resp.verified && resp.hasError()) {
      throw ConnectibleException.fromError(resp.error);
    }
    return resp.verified;
  }

  Future<List<DeviceInfo>> listDevices() async {
    final resp =
        await _client.listDevices(pb.ListDevicesRequest(onlineOnly: false));
    return resp.devices.map((d) {
      final identity = d.identity;
      return DeviceInfo(
        deviceId: identity.deviceId,
        deviceName: identity.deviceName,
        online: d.online,
        pairedAtMs: d.pairedAtMs.toInt(),
        lastSeenMs: d.lastSeenMs.toInt(),
        // Carry the peer's platform so the paired-device UI can render its
        // platform icon (T-E6), labelled the same way mDNS/Identity are.
        platform: DeviceListModel.platformName(identity.platform),
      );
    }).toList(growable: false);
  }

  /// Opens the bidirectional SyncStream. Callers push frames on
  /// [outbound] (clipboard, file chunks, input events) and listen to
  /// the returned response stream for incoming frames.
  Stream<pb.SyncFrame> openSyncStream(Stream<pb.SyncFrame> outbound) {
    return _client.syncStream(outbound);
  }

  Future<void> shutdown() => _channel.shutdown();
}

/// TOFU handshake state (T-C4), shared between the `onBadCertificate`
/// callback and the owning [GrpcService]. The callback is synchronous and
/// cannot reach an async store, so it only compares against the pin passed
/// in and records what it saw; the caller persists on first use.
class _TofuState {
  _TofuState({this.pinned});

  /// Expected fingerprint (lowercase hex SHA-256 of the cert DER), or null
  /// for first contact / an unpinned device.
  final String? pinned;

  /// The fingerprint actually presented, filled in during the handshake.
  String? observed;

  /// Set when a pin existed and the presented cert did not match it.
  bool mismatch = false;

  /// The `onBadCertificate` decision: always records the observed
  /// fingerprint; rejects (returns false) only on a pin mismatch, so a
  /// re-keyed peer or imposter cannot complete the handshake.
  bool accept(X509Certificate cert) {
    final fingerprint = sha256.convert(cert.der).toString();
    observed = fingerprint;
    if (pinned != null && pinned != fingerprint) {
      mismatch = true;
      return false;
    }
    return true;
  }
}
