use std::io::SeekFrom;
use std::path::Path;
use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};
use std::sync::Arc;

use connectibled::proto::connectible::v1::connectible_client::ConnectibleClient;
use connectibled::proto::connectible::v1::sync_frame::Payload;
use connectibled::proto::connectible::v1::upload_file_part::Part as UploadPart;
use connectibled::proto::connectible::v1::{
    ConfirmPinRequest, ErrorCode, Identity, InputEventType, MouseButton, PairRequest,
    PrepareUploadRequest, RemoteInputEvent, SyncFrame, UploadFileHeader, UploadFileMeta,
    UploadFilePart,
};
use connectibled::transfer;
use sha2::{Digest, Sha256};
use tokio::io::{AsyncReadExt, AsyncSeekExt};
use tokio::sync::{mpsc, Notify};
use tokio_stream::wrappers::ReceiverStream;
use tonic::transport::{Channel, ClientTlsConfig};

/// Chunk size for the dedicated upload stream. Larger than the old 64KB
/// SyncStream chunk since there is no per-chunk CRC/framing overhead here
/// -- just raw bytes the receiver appends -- so bigger reads mean fewer
/// awaits without hurting backpressure (the stream still flow-controls).
const UPLOAD_CHUNK_BYTES: usize = 256 * 1024;

/// A fresh transfer id. Generated by the caller (not inside `send_file`)
/// so it can register a cancel handle *before* the send starts, closing
/// the race where a cancel arrives before the id is known.
pub fn new_transfer_id() -> String {
    uuid::Uuid::new_v4().to_string()
}

/// Walks an error's `source()` chain looking for `needle`. The TLS
/// verifier's rejection reason (e.g. the TOFU FINGERPRINT_CHANGED marker)
/// is nested several layers deep inside a `tonic::transport::Error`, so the
/// top-level `Display` alone does not reveal it.
fn error_chain_mentions(err: &(dyn std::error::Error + 'static), needle: &str) -> bool {
    let mut current: Option<&(dyn std::error::Error + 'static)> = Some(err);
    while let Some(e) = current {
        if e.to_string().contains(needle) {
            return true;
        }
        current = e.source();
    }
    false
}

/// Whole-file SHA-256 (hex), computed by streaming the file so a large
/// upload never buffers it in RAM just to declare its hash in
/// `PrepareUpload`. Matches the daemon receiver's own streaming digest
/// byte-for-byte.
async fn hash_file(path: &Path) -> Result<String> {
    let mut file = tokio::fs::File::open(path).await?;
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; UPLOAD_CHUNK_BYTES];
    loop {
        let n = file.read(&mut buf).await?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(hex::encode(hasher.finalize()))
}

use crate::dto::TransferProgressDto;
use crate::tls::TofuVerifier;
use crate::{DesktopError, Result};

/// Client for a *remote* Connectible daemon (another machine on the
/// LAN), used for the requester side of pairing (T-010, T-045-equiv),
/// outgoing file transfers, and remote input sessions.
#[derive(Clone)]
pub struct RemoteDeviceClient {
    client: ConnectibleClient<Channel>,
    /// TOFU (T-C2): the peer server cert fingerprint observed during the
    /// TLS handshake. `Some` after a successful connect; the caller pins it
    /// on first use (or has already verified it matched the pin).
    observed_fingerprint: std::sync::Arc<std::sync::Mutex<Option<String>>>,
}

/// Outcome of a pair() call, mirrored to the frontend.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PairOutcome {
    pub accepted: bool,
    /// 0 means "already paired, no PIN entry needed" (the responder's
    /// duplicate-pairing short-circuit, T-015).
    pub pin_expires_at_ms: i64,
}

impl RemoteDeviceClient {
    /// Connects to `addr:port` over TLS 1.3 with no pin (first contact /
    /// pairing). The peer's cert is accepted and recorded; read it back
    /// with [`observed_fingerprint`](Self::observed_fingerprint) to pin it.
    pub async fn connect(addr: &str, port: u16) -> Result<Self> {
        Self::connect_pinned(addr, port, None).await
    }

    /// Connects to `addr:port` over TLS 1.3, enforcing TOFU (T-C2/C3): if
    /// `pinned` is `Some`, the peer's certificate fingerprint must match it
    /// or the handshake is rejected with `FINGERPRINT_CHANGED`. Either way
    /// the observed fingerprint is captured for the caller to pin.
    pub async fn connect_pinned(
        addr: &str,
        port: u16,
        pinned: Option<String>,
    ) -> Result<Self> {
        let endpoint = format!("https://{addr}:{port}");
        let (verifier, observed) = TofuVerifier::new(pinned);
        let channel = match Channel::from_shared(endpoint)
            .map_err(|e| DesktopError::InvalidAddress(e.to_string()))?
            .tls_config_with_verifier(ClientTlsConfig::new(), verifier)?
            // Keep long-lived SyncStreams (file sends, input sessions)
            // alive across NAT idle timeouts and detect half-open drops.
            .http2_keep_alive_interval(std::time::Duration::from_secs(20))
            .keep_alive_timeout(std::time::Duration::from_secs(10))
            .keep_alive_while_idle(true)
            .connect()
            .await
        {
            Ok(channel) => channel,
            // TOFU (T-C3): the verifier rejects a changed pin with a
            // FINGERPRINT_CHANGED marker buried in the TLS error chain.
            // Surface it as a precise, actionable ErrorCode rather than a
            // generic transport failure.
            Err(e) if error_chain_mentions(&e, "FINGERPRINT_CHANGED") => {
                return Err(DesktopError::Remote {
                    code: ErrorCode::FingerprintChanged,
                    message: "the peer's security certificate changed since pairing".to_string(),
                });
            }
            Err(e) => return Err(e.into()),
        };

        Ok(Self {
            client: ConnectibleClient::new(channel),
            observed_fingerprint: observed,
        })
    }

    /// The peer server cert fingerprint seen during the handshake, if the
    /// connection succeeded (TOFU, T-C2). Used to record-on-first-use.
    pub fn observed_fingerprint(&self) -> Option<String> {
        self.observed_fingerprint
            .lock()
            .ok()
            .and_then(|slot| slot.clone())
    }

    /// Requester side of pairing: asks the remote device to show its
    /// PIN dialog. The user then reads the PIN off the remote screen
    /// and this client submits it via `confirm_pin`.
    pub async fn pair(&self, local_identity: Identity) -> Result<PairOutcome> {
        let mut client = self.client.clone();
        let response = client
            .pair(PairRequest {
                requester: Some(local_identity),
            })
            .await?
            .into_inner();

        if let Some(error) = response.error {
            // T-602: preserve the responder's exact ErrorCode (e.g.
            // RATE_LIMITED from the T-403 pairing throttle) instead of
            // collapsing it to DesktopError::Other, which would have
            // forced the desktop side back to a lossy tonic::Code
            // inference it doesn't even have here (this isn't a
            // tonic::Status, it's a structured proto Error field).
            let code = ErrorCode::try_from(error.code).unwrap_or(ErrorCode::Unspecified);
            return Err(DesktopError::Remote {
                code,
                message: error.message,
            });
        }
        Ok(PairOutcome {
            accepted: response.accepted,
            pin_expires_at_ms: response.pin_expires_at_ms,
        })
    }

    pub async fn confirm_pin(&self, device_id: &str, pin_code: &str) -> Result<bool> {
        let mut client = self.client.clone();
        let response = client
            .confirm_pin(ConfirmPinRequest {
                device_id: device_id.to_string(),
                pin_code: pin_code.to_string(),
            })
            .await?
            .into_inner();
        Ok(response.verified)
    }

    /// Sends a file to the remote device over a fresh SyncStream,
    /// reporting outgoing progress through `progress`. Progress events
    /// are derived by intercepting the chunk frames the shared
    /// `connectibled::transfer::send_file_with_resend` produces, so the
    /// sender logic itself stays single-sourced in the daemon crate.
    ///
    /// `start_offset` resumes a previously-interrupted send (T-025):
    /// pass the byte count the caller last saw acknowledged for this
    /// `transfer_id` (0 for a fresh transfer). The receiver reuses its
    /// on-disk partial file for the same `transfer_id`, so re-sending
    /// from 0 would only waste bandwidth, not corrupt anything -- but
    /// resuming from the real offset is what makes T-025 actually work
    /// end-to-end instead of just being supported on the receive side.
    ///
    /// T-306: while the send is in flight, an inbound `FileChunkRequest`
    /// (the peer detected a corrupted chunk via CRC32) is forwarded to
    /// `send_file_with_resend`, which reuses its already-open file
    /// handle to resend just that chunk -- distinct from the coarser
    /// T-025 whole-transfer resume path.
    pub async fn send_file(
        &self,
        path: &Path,
        local_identity: Identity,
        progress: mpsc::Sender<TransferProgressDto>,
        transfer_id: String,
        cancel: Arc<Notify>,
        start_offset: i64,
    ) -> Result<String> {
        let file_name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("file")
            .to_string();
        let total_bytes = tokio::fs::metadata(path).await?.len() as i64;

        // Frames flow: send_file_with_resend -> intercept channel
        // (progress accounting) -> outbound gRPC stream.
        let (frame_tx, mut frame_rx) = mpsc::channel::<SyncFrame>(16);
        let (grpc_tx, grpc_rx) = mpsc::channel::<SyncFrame>(16);

        // Bytes acked by the forwarder, so a cancel can report where the
        // transfer stopped instead of jumping the progress bar to 0.
        // Seeded from `start_offset` so a resumed send's progress bar
        // starts where it actually left off, not back at 0.
        let sent = Arc::new(AtomicI64::new(start_offset));
        let progress_id = transfer_id.clone();
        let progress_name = file_name.clone();
        let sent_counter = sent.clone();
        // Kept for the cancel path, since the forwarder takes `progress`.
        let progress_cancel = progress.clone();
        let forwarder = tokio::spawn(async move {
            let mut sent_bytes: i64 = start_offset;
            let mut last_emit = std::time::Instant::now() - std::time::Duration::from_secs(1);
            while let Some(frame) = frame_rx.recv().await {
                if let Some(Payload::FileChunk(chunk)) = &frame.payload {
                    sent_bytes = sent_bytes.max(chunk.offset_bytes + chunk.data.len() as i64);
                    sent_counter.store(sent_bytes, Ordering::Relaxed);
                    let done = chunk.is_last;
                    // Same UI-facing throttle as the daemon's incoming
                    // progress (T-027): at most ~4 events/second, but
                    // the final event always fires.
                    if done || last_emit.elapsed() >= std::time::Duration::from_millis(250) {
                        last_emit = std::time::Instant::now();
                        let _ = progress
                            .send(TransferProgressDto {
                                transfer_id: progress_id.clone(),
                                file_name: progress_name.clone(),
                                bytes_transferred: sent_bytes,
                                total_bytes,
                                completed: done,
                                failed: false,
                                canceled: false,
                                direction: "outgoing".to_string(),
                            })
                            .await;
                    }
                }
                if grpc_tx.send(frame).await.is_err() {
                    break;
                }
            }
        });

        let mut client = self.client.clone();
        let outbound = ReceiverStream::new(grpc_rx);
        let response_stream = client.sync_stream(outbound).await?;

        // Identity first (stream protocol: identify before data frames),
        // then the chunked file.
        frame_tx
            .send(SyncFrame {
                payload: Some(Payload::Identity(local_identity)),
            })
            .await
            .map_err(|_| DesktopError::Other("sync stream closed before send".to_string()))?;

        // T-306: read the peer's response stream concurrently with the
        // send below (rather than only after, as before this change),
        // since a FileChunkRequest can arrive mid-transfer and needs to
        // reach send_file_with_resend while it is still running.
        // Forwards each FileChunkRequest as a ResendRequest and remembers
        // the first Error frame (e.g. checksum mismatch, once resend
        // attempts are exhausted) to surface as this call's failure.
        let (resend_tx, resend_rx) = mpsc::channel::<transfer::ResendRequest>(8);
        let mut inbound = response_stream.into_inner();
        let inbound_task = tokio::spawn(async move {
            let mut peer_error: Option<String> = None;
            while let Ok(Some(frame)) = inbound.message().await {
                match frame.payload {
                    Some(Payload::FileChunkRequest(req)) => {
                        let _ = resend_tx
                            .send(transfer::ResendRequest {
                                transfer_id: req.transfer_id,
                                offset_bytes: req.offset_bytes,
                            })
                            .await;
                    }
                    Some(Payload::Error(error)) => {
                        peer_error = Some(error.message);
                        break;
                    }
                    _ => {}
                }
            }
            peer_error
        });

        // Race the chunked send against a user cancel. On cancel we stop
        // feeding chunks (dropping frame_tx ends the outbound stream) and
        // emit a terminal "canceled" progress so the UI settles. The send
        // future is scoped so it (and its borrow of frame_tx) is dropped
        // before frame_tx below.
        let canceled = {
            let send = transfer::send_file_with_resend(
                &frame_tx,
                Some(resend_rx),
                path,
                transfer_id.clone(),
                start_offset,
            );
            tokio::pin!(send);
            tokio::select! {
                r = &mut send => {
                    r.map_err(|e| DesktopError::Other(format!("file send failed: {e}")))?;
                    false
                }
                _ = cancel.notified() => {
                    let _ = progress_cancel
                        .send(TransferProgressDto {
                            transfer_id: transfer_id.clone(),
                            file_name: file_name.clone(),
                            bytes_transferred: sent.load(Ordering::Relaxed),
                            total_bytes,
                            completed: false,
                            failed: true,
                            canceled: true,
                            direction: "outgoing".to_string(),
                        })
                        .await;
                    true
                }
            }
        };

        drop(frame_tx);
        forwarder
            .await
            .map_err(|e| DesktopError::Other(format!("progress forwarder panicked: {e}")))?;

        if canceled {
            inbound_task.abort();
            return Ok(transfer_id);
        }

        // The peer's response stream closes shortly after it sees our
        // outbound close (dropped above); collect whatever the inbound
        // task saw in the meantime.
        if let Some(message) = inbound_task
            .await
            .map_err(|e| DesktopError::Other(format!("inbound reader panicked: {e}")))?
        {
            return Err(DesktopError::Other(format!(
                "peer rejected transfer: {message}"
            )));
        }

        Ok(transfer_id)
    }

    /// Uploads a file over the dedicated `PrepareUpload` + `UploadFile`
    /// RPCs (TASKS.md Phase A) instead of chunk-framing it onto
    /// `SyncStream`. Bytes stream one-way on their own client-streaming
    /// RPC, so a control-stream reconnect can't kill the transfer and
    /// HTTP/2 flow control is the backpressure (the feeder awaits each
    /// send). The resume offset comes from the receiver's `PrepareUpload`
    /// answer (bytes it already holds), not the caller. A `cancel` notify
    /// stops the feeder early, leaving a resumable partial on the peer.
    pub async fn upload_file(
        &self,
        path: &Path,
        local_identity: Identity,
        progress: mpsc::Sender<TransferProgressDto>,
        file_id: String,
        cancel: Arc<Notify>,
    ) -> Result<String> {
        let file_name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("file")
            .to_string();
        let total_bytes = tokio::fs::metadata(path).await?.len() as i64;
        let file_hash = hash_file(path).await?;

        // Step 1: PrepareUpload -- declare the file, learn accept + resume.
        let mut client = self.client.clone();
        let prepared = client
            .prepare_upload(PrepareUploadRequest {
                sender: Some(local_identity),
                session_id: file_id.clone(),
                files: vec![UploadFileMeta {
                    file_id: file_id.clone(),
                    file_name: file_name.clone(),
                    file_size_bytes: total_bytes,
                    file_hash,
                    mime_type: "application/octet-stream".to_string(),
                }],
            })
            .await?
            .into_inner();

        let offer = prepared
            .offers
            .into_iter()
            .find(|o| o.file_id == file_id)
            .ok_or_else(|| DesktopError::Other("receiver returned no offer".to_string()))?;
        if !offer.accepted {
            return Err(DesktopError::Remote {
                code: ErrorCode::FileTransferFailed,
                message: format!("receiver declined the file: {}", offer.reject_reason),
            });
        }
        let session_id = prepared.session_id;
        let resume_offset = offer.resume_offset_bytes.max(0);
        let token = offer.token;

        // A cancel notify flips a flag the feeder polls, so cancelling
        // ends the stream cleanly (leaving a resumable partial) rather
        // than aborting the RPC mid-frame.
        let cancel_flag = Arc::new(AtomicBool::new(false));
        {
            let flag = cancel_flag.clone();
            tokio::spawn(async move {
                cancel.notified().await;
                flag.store(true, Ordering::Relaxed);
            });
        }

        // Step 2: UploadFile -- header, then raw bytes from the resume
        // offset, fed on an mpsc so `ReceiverStream` drives the client
        // stream (same pattern as send_file's outbound, no async-stream dep).
        let (part_tx, part_rx) = mpsc::channel::<UploadFilePart>(8);
        let feeder_path = path.to_path_buf();
        let feeder_progress = progress.clone();
        let feeder_flag = cancel_flag.clone();
        let feeder_name = file_name.clone();
        let feeder_id = file_id.clone();
        let feeder = tokio::spawn(async move {
            let header = UploadFilePart {
                part: Some(UploadPart::Header(UploadFileHeader {
                    session_id,
                    file_id: feeder_id.clone(),
                    token,
                    offset_bytes: resume_offset,
                })),
            };
            if part_tx.send(header).await.is_err() {
                return;
            }

            let mut file = match tokio::fs::File::open(&feeder_path).await {
                Ok(f) => f,
                Err(_) => return,
            };
            if resume_offset > 0 && file.seek(SeekFrom::Start(resume_offset as u64)).await.is_err() {
                return;
            }
            let mut sent = resume_offset;
            let mut buf = vec![0u8; UPLOAD_CHUNK_BYTES];
            let mut last_emit = std::time::Instant::now() - std::time::Duration::from_secs(1);
            loop {
                if feeder_flag.load(Ordering::Relaxed) {
                    break;
                }
                let n = match file.read(&mut buf).await {
                    Ok(0) => break,
                    Ok(n) => n,
                    Err(_) => break,
                };
                let part = UploadFilePart {
                    part: Some(UploadPart::Chunk(buf[..n].to_vec())),
                };
                if part_tx.send(part).await.is_err() {
                    break;
                }
                sent += n as i64;
                if last_emit.elapsed() >= std::time::Duration::from_millis(250) {
                    last_emit = std::time::Instant::now();
                    let _ = feeder_progress
                        .send(TransferProgressDto {
                            transfer_id: feeder_id.clone(),
                            file_name: feeder_name.clone(),
                            bytes_transferred: sent,
                            total_bytes,
                            completed: false,
                            failed: false,
                            canceled: false,
                            direction: "outgoing".to_string(),
                        })
                        .await;
                }
            }
            // part_tx dropped here -> the client stream ends.
        });

        let result = client
            .upload_file(ReceiverStream::new(part_rx))
            .await?
            .into_inner();
        let _ = feeder.await;

        let canceled = cancel_flag.load(Ordering::Relaxed);
        let terminal = |completed: bool, failed: bool, canceled: bool, bytes: i64| TransferProgressDto {
            transfer_id: file_id.clone(),
            file_name: file_name.clone(),
            bytes_transferred: bytes,
            total_bytes,
            completed,
            failed,
            canceled,
            direction: "outgoing".to_string(),
        };

        if result.completed && result.hash_ok {
            let _ = progress.send(terminal(true, false, false, total_bytes)).await;
            Ok(file_id)
        } else if canceled {
            let _ = progress
                .send(terminal(false, true, true, result.bytes_received))
                .await;
            Ok(file_id)
        } else {
            let _ = progress
                .send(terminal(false, true, false, result.bytes_received))
                .await;
            // All bytes arrived but the whole-file hash didn't match ->
            // checksum mismatch; otherwise the stream fell short -> a
            // generic transfer failure. Mapped to real ErrorCodes so the
            // UI shows an actionable message, not a raw string.
            let code = if result.bytes_received >= total_bytes {
                ErrorCode::ChecksumMismatch
            } else {
                ErrorCode::FileTransferFailed
            };
            Err(DesktopError::Remote {
                code,
                message: "upload failed to complete or verify".to_string(),
            })
        }
    }

    /// Opens a long-lived SyncStream dedicated to remote input events
    /// and returns a handle for pushing them (T-048-equivalent for the
    /// desktop-as-controller direction).
    pub async fn open_input_session(&self, local_identity: Identity) -> Result<InputSession> {
        let (tx, rx) = mpsc::channel::<SyncFrame>(64);
        let mut client = self.client.clone();
        let outbound = ReceiverStream::new(rx);
        // The response stream is intentionally dropped: input is
        // fire-and-forget and the server sends nothing back for it.
        let _response = client.sync_stream(outbound).await?;

        tx.send(SyncFrame {
            payload: Some(Payload::Identity(local_identity)),
        })
        .await
        .map_err(|_| DesktopError::Other("input stream closed immediately".to_string()))?;

        Ok(InputSession { tx })
    }
}

/// Handle to an open remote-input SyncStream. Dropping it closes the
/// stream (the channel sender is the only thing keeping it open).
pub struct InputSession {
    tx: mpsc::Sender<SyncFrame>,
}

impl InputSession {
    async fn send(&self, event: RemoteInputEvent) -> Result<()> {
        self.tx
            .send(SyncFrame {
                payload: Some(Payload::InputEvent(event)),
            })
            .await
            .map_err(|_| DesktopError::Other("input session closed".to_string()))
    }

    /// `x`, `y` normalized to [0.0, 1.0] per the wire contract.
    pub async fn mouse_move(&self, x: f32, y: f32) -> Result<()> {
        self.send(RemoteInputEvent {
            r#type: InputEventType::MouseMove as i32,
            x,
            y,
            ..Default::default()
        })
        .await
    }

    pub async fn mouse_button(&self, button: MouseButton, pressed: bool) -> Result<()> {
        self.send(RemoteInputEvent {
            r#type: InputEventType::MouseButton as i32,
            button: button as i32,
            pressed,
            ..Default::default()
        })
        .await
    }

    pub async fn scroll(&self, delta_x: f32, delta_y: f32) -> Result<()> {
        self.send(RemoteInputEvent {
            r#type: InputEventType::MouseScroll as i32,
            scroll_delta_x: delta_x,
            scroll_delta_y: delta_y,
            ..Default::default()
        })
        .await
    }

    pub async fn key(&self, key_code: u32, pressed: bool) -> Result<()> {
        self.send(RemoteInputEvent {
            r#type: InputEventType::Key as i32,
            key_code,
            key_pressed: pressed,
            ..Default::default()
        })
        .await
    }
}
